id: P010486
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4249
  title: རྗེ་བཙུན་བླ་མ་དམ་པ་ཁམས་གསུམ་ཆོས་ཀྱི་རྒྱལ་པོ་ངག་དབང་ཡོན་ཏན་བཟང་པོའི་རྣམ་ཐར།
  author: ''
  volumes:
    c471e4b6a53c410892f8afca4648f3f4:
      image_group_id: I1KG4969
      title: ''
      volume_number: 1
      total_pages: 314
